+incdir+../RTL/Decoder/
../testbench/testbench.sv
../RTL/Core/CoreTop.v
../RTL/Core/ForwardUnit.v
../RTL/PC_IF/InstFetch.v
../RTL/PC_IF/PcGen.v
../RTL/PC_IF/BranchPredict.v
../RTL/Decoder/DecoderTop.v
../RTL/Decoder/FunctionDecoder.v
../RTL/Decoder/TypeDecoder.v
../RTL/OperandRegister/RegisterTop.v
../RTL/OperandRegister/Register32.v
../RTL/ALU/ALUTop.v
../RTL/ALU/ALU.v
../RTL/ALU/LSU.v
../RTL/WriteBack/WriteBack.v
../RTL/CoreBus/CoreBus.v
../RTL/Memory/MemoryModel.v
../RTL/CSR/CSR.v
../RTL/CSR/CSRTop.v
